import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from './layoutComponents/Header';
import Footer from './layoutComponents/Footer';
import QueryProvider from './layoutComponents/QueryProvider';
import { GoogleOAuthProvider } from '@react-oauth/google';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
            >
                <QueryProvider>
                    <GoogleOAuthProvider clientId={process.env.GOOGLE_DEV_CLIENT_ID!}>
                        <Header />
                        <main className="flex-1 py-[48px] w-full h-auto flex flex-col justify-start items-center">
                            {children}
                        </main>
                        <Footer />
                    </GoogleOAuthProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
