import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from './layoutComponents/Header';
import Footer from './layoutComponents/Footer';
import QueryProvider from './layoutComponents/QueryProvider';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
            >
                <Header />
                <QueryProvider>
                    <main className="flex-1 py-[48px]">{children}</main>
                </QueryProvider>
                <Footer />
            </body>
        </html>
    );
}
