name: Deploy Frontend to Nginx Home Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install
              working-directory: frontend

            - name: Build project
              run: npm run build
              working-directory: frontend

            - name: Transfer build artifacts to Nginx Home Server
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER }}
                  username: ${{ secrets.USER_NAME }}
                  key: ${{ secrets.SSH_KEY }}
                  source: '/frontend/.next/,/frontend/public/,/frontend/package.json,/frontend/next.config.js'
                  target: '/home/yohan/portcloud/frontend'

    
            - name: Next.js restart Nginx reload
              uses: appleboy/ssh-action@master 
              with:
                    host: ${{ secrets.SERVER }}
                    username: ${{ secrets.USER_NAME }}
                    key: ${{ secrets.SSH_KEY }}
                    script: |
                       cd /home/yohan/portcloud/frontend
                       pm2 restart portcloud
                       
